api:
  - any: ["frontend/src/ts/ape/**/*", "backend/src/api/**/*"]

assets:
  - all: ["frontend/static/**/*", "!frontend/static/**/*.html"]

backend:
  - any: ["backend/**/*"]

docs:
  - any: ["**/*.md"]

frontend:
  - any: ["frontend/**/*"]

local dev:
  - any: ["**/gulpfile.js", "**/tsconfig.json"]
