version: "3.8"
services:
  monkeytype-frontend:
    container_name: monkeytype-frontend
    image: node:16.13-alpine
    restart: on-failure
    ports:
      - "80:5000"
    volumes:
      - ./:/monkeytype
    entrypoint: 'sh -c "cd /monkeytype/frontend && npm run live"'
    depends_on:
      - monkeytype-backend

  monkeytype-backend:
    container_name: monkeytype-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "5005:5005"
    volumes:
      - ./:/monkeytype
    depends_on:
      - monkeytype-redis

  monkeytype-redis:
    container_name: monkeytype-redis
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    restart: on-failure
    command: "redis-server --save 30 1 --loglevel warning"
    volumes:
      - redis-data:/data/redis

  monkeytype-mongodb:
    container_name: monkeytype-mongodb
    image: mongo:5.0.8
    restart: on-failure
    volumes:
      - mongo-data:/data/mongo
    ports:
      - "27017:27017"

volumes:
  redis-data:
  mongo-data:
networks:
  test-network:
