version: "3.8"
services:
  monkeytype-frontend:
    container_name: monkeytype-frontend
    image: node:gallium-bullseye
    restart: on-failure
    ports:
      - "3000:3000"
    volumes:
      - ./:/monkeytype
    entrypoint: 'bash -c "cd /monkeytype && npm run dev-fe"'
    depends_on:
      - monkeytype-backend

  monkeytype-backend:
    container_name: monkeytype-backend
    image: node:gallium-bullseye
    restart: on-failure
    ports:
      - "3000:3000"
    volumes:
      - ./:/monkeytype
    entrypoint: 'bash -c "cd /monkeytype && npm run dev-be"'
    depends_on:
      - monkeytype-redis
      - monkeytype-mongodb

  monkeytype-redis:
    container_name: monkeytype-redis
    image: redis:6.2.6
    ports:
      - "${DOCKER_REDIS_PORT:-6379}:${DOCKER_REDIS_PORT:-6379}"
    restart: on-failure
    volumes:
      - redis-data:/data/redis
    networks:
      - test-network

  monkeytype-mongodb:
    container_name: monkeytype-mongodb
    image: mongo:5.0.8
    restart: on-failure
    volumes:
      - mongo-data:/data/mongo
    ports:
      - "${DOCKER_DB_PORT:-27017}:${DOCKER_DB_PORT:-27017}"
    networks:
      - test-network

volumes:
  mongo-data:
  redis-data:
networks:
  test-network:
